# -*- coding: utf-8 -*-
"""SPRINT03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1129KzgjFuWqOiqCf5xS9mSlTVyxRul9Z
"""

import scipy
from scipy.stats import norm
import pandas as pd
import numpy as np
import seaborn as sns
import statsmodels



#CASO NECESSARIO POR FAVOR ALTERE O CAMINHO DO ARQUIVO DA PLANILHA DOS DADOS PARA A ATUAL LOCALIZAÇÃO NO SEU COMPUTADOR
#CASO NECESSARIO CERTIFIQUE QUE A BASE DE DADOS ESTÁ PRESENTE NO GOOGLE COLAB, BASTA ANEXAR O ARQUIVO AO MENU A ESQUERDA
dados = pd.read_excel(r'/content/base_dados_clientes_completa.xlsx')

print(dados.head())
print("\n")

#A)CALCULO DA MEDIANA:

df = pd.read_excel(r'/content/base_dados_clientes_completa.xlsx')
coluna_days = df['Days_Since_Subscription']
coluna_login = df['Avg_Login_Time']
mediana_days = coluna_days.median()
print(f"A mediana da coluna 'Days_Since_Subscription' é: {mediana_days}")
print("\n")



#B)CALCULO DA PROBABILIDADE:
media_days = coluna_days.mean()
desvio_padrao_days = coluna_days.std()

print("_" * 30)
print(f"Média: {media_days:.2f}")
print(f"Desvio Padrão: {desvio_padrao_days:.2f}")
print("_" * 30)
#print("\n")

#probabilidade
probabilidade = scipy.stats.norm.cdf(1534.0, loc=media_days, scale=desvio_padrao_days)
print(f"a probabilidade de 'Days_Since_Subscription' ser menor que 1534 é {probabilidade:.2f}, sendo assim: provavel")

#2)
limite_inferior = media_days - (2 * desvio_padrao_days)
limite_superior = media_days + (2 * desvio_padrao_days)

print(f"Intervalo de 2 desvios padrão em torno da média para 'Days_Since_Subscription':")
print(f"De {limite_inferior:.2f} até {limite_superior:.2f}")
print("\n")

probabilidade_inf = scipy.stats.norm.cdf(limite_inferior, loc=media_days, scale=desvio_padrao_days)
print(f"a probabilidade de 'Days_Since_Subscription' ser menor que {limite_inferior:.2f} é {probabilidade_inf:.2f}, sendo assim: raro")
probabilidade_sup = scipy.stats.norm.cdf(limite_superior, loc=media_days, scale=desvio_padrao_days)
print(f"a probabilidade de 'Days_Since_Subscription' ser menor que {limite_superior:.2f} é {probabilidade_sup:.2f}, sendo assim: quase certo")

#3
print("\n")
dataset = pd.DataFrame({'Days_Since_Subscription': coluna_days, 'Avg_Login_Time': coluna_login})
dataset.head()

import statsmodels.api as sm

Y = dataset['Days_Since_Subscription']
X = sm.add_constant(dataset['Avg_Login_Time'])


resultado_regressao = sm.OLS(Y, X).fit()
print(resultado_regressao.summary())

dataset['Y_previsto'] = resultado_regressao.predict()
dataset

ax = sns.lmplot(x="Avg_Login_Time", y="Days_Since_Subscription", data=dataset)
ax.fig.set_size_inches(12, 6)
ax.fig.suptitle('Reta de Regressão - Avg_Login_Time X Days_Since_Subscription', fontsize=16, y=1.02)
ax.set_xlabels("Avg_Login_Time", fontsize=14)
ax.set_ylabels("Days_Since_Subscription", fontsize=14)

ax = sns.boxplot(data=dataset, orient='h', width=0.5)
ax.figure.set_size_inches(12, 6)
ax.set_title('Box plot', fontsize=20)
ax.set_xlabel('Reais (R$)', fontsize=16)